import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import GeneralProviders from "@/shared/providers/GeneralProviders";

const barlow = Barlow({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

// const barlowCondensed = Barlow_Condensed({
//   variable: "--font-barlow-condensed",
//   subsets: ["latin"],
// });

// const barlowSemiCondensed = Barlow_Semi_Condensed({
//   variable: "--font-barlow-semi-condensed",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.className} antialiased`}>
        <GeneralProviders>{children}</GeneralProviders>
      </body>
    </html>
  );
}
